language: cpp
os: linux
compiler:
  - clang
  - gcc

dist: bionic

addons:
  apt:
    packages:
    - python3-dev
    - ninja-build

# the install step will take care of deploying a newer cmake version
install:    
  - which python3
  - which python
  - python3 --version
  - python --version
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.16.4/cmake-3.16.4-Linux-x86_64.tar.gz
  - tar -xvf cmake-3.16.4-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.16.4-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - cmake --version
  - ninja --version
  - mkdir build
  - cmake -GNinja -S . -B build
  - cd build

script:
  - ninja
  - ctest
